-- Active: 1657234173046@@127.0.0.1@3306@stream
CREATE DATABASE STAART;

USE STAART;

CREATE SCHEMA STREAM;

CREATE TABLE MANTIMENTO(
	NOME VARCHAR(200),
	DATA_DE_VALIDADE DATE
);

CREATE TABLE STREAM.ELETRONICOS(
	NOME VARCHAR(200),
	DESCRICAO VARCHAR(200)
);

CREATE TABLE STREAM.USERS( -- Tabela de usuários.
	ID_USER INT PRIMARY KEY,
    NAME VARCHAR(255),
    USERNAME VARCHAR(255),
    PASSWORD VARCHAR(100),
    CREATED_AT DATETIME
);

CREATE TABLE STREAM.CATEGORIES( -- Categoria de produtos.
	ID_CATEGORY INT AUTO_INCREMENT PRIMARY KEY, -- ID da categoria.
	NAME VARCHAR(255) UNIQUE NOT NULL -- Nome da categoria.
);

INSERT INTO STREAM.CATEGORIES(NAME) VALUES("COMEDIA"); -- Adciona nova categoria.

-- SELECT
SELECT *
FROM STREAM.CATEGORIES
WHERE ID_CATEGORY > 1;

INSERT INTO STREAM.USERS(ID_USER, NAME, USERNAME, PASSWORD, CREATED_AT) -- Adicionando um usuário.
VALUES(3, "DANIEL", "DAN", NULL, CURRENT_DATE());

SELECT *
FROM STREAM.USERS;

-- UPDATE
UPDATE STREAM.USERS
SET PASSWORD = "5678" -- Atualiza a senha do usuário.
WHERE ID_USER = 2; -- Atualiza o usuário com o ID 2.

-- DELETE
DELETE 
FROM STREAM.CATEGORIES 
WHERE ID_CATEGORY = 4;

-- ALTER TABLE
ALTER TABLE STREAM.USERS -- Alterar o nome do campo.
ADD CONSTRAINT NAME_UNIQUE UNIQUE (NAME); -- Nome deve ser único.

-- IN
SELECT * FROM STREAM.CATEGORIES
WHERE ID_CATEGORY IN (1, 3, 6);

-- BETWEEN
SELECT * FROM STREAM.CATEGORIES
WHERE ID_CATEGORY BETWEEN 3 AND 6;

-- != <>
SELECT * FROM STREAM.CATEGORIES
WHERE ID_CATEGORY != 3;

-- IS NULL / IS NOT NULL
SELECT * FROM STREAM.USERS
WHERE PASSWORD IS NULL;

SELECT * FROM STREAM.USERS
WHERE PASSWORD IS NOT NULL;

-- LIKE
SELECT * FROM STREAM.USERS
WHERE USERNAME LIKE 'DAN%'; -- Busca usuários com o nome que contenha DAN | O uso do '%' é para expecificar se começa/termina ou contenha em qualquer parte o valor buscado.

-- > <
SELECT * FROM STREAM.USERS
WHERE ID_USER < 4;